; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:adafruit_feather_esp32s3_nopsram]
platform = espressif32
board = adafruit_feather_esp32s3_nopsram
framework = arduino
lib_deps = 
	adafruit/Adafruit GFX Library@^1.12.1
	mrfaptastic/ESP32 HUB75 LED MATRIX PANEL DMA Display@^3.0.12
	mathertel/RotaryEncoder@^1.6.0
